name: kosac_delivery_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.3
  flutter_localizations:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.17.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/kosac_delivery_app_splash_screen_logo.png
    - assets/delivery_partner_logo.png
    - assets/lang/  # ✅ JSON files for localization
    - assets/lang/en.json
    - assets/lang/hi.json
    - assets/lang/mr.json
    - assets/homescreen_delivery_app.png
    
